FROM python:3.12-slim

WORKDIR /app

# Instala ferramentas essenciais do sistema para compilação (necessário para pgvector/psycopg2)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./backend /app

# Instala o gerenciador UV e injeta todas as dependências no sistema do container de forma definitiva
RUN pip install --no-cache-dir uv && \
    uv pip install --system \
    fastapi \
    uvicorn \
    ollama \
    chromadb \
    sentence-transformers \
    psycopg2-binary \
    sqlalchemy \
    watchfiles \
    pypdf \
    python-multipart

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
